### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [josephxbrick/TabBar#1]
Good day Sir @josephxbrick  I am a graphic designer and i want to propose a logo design for your nice project. Ill be doing it for free as my gift to the project. If you will allow me I will start designing asap.

Thanks and best regards!
-Tobaloidee

**Comment by josephxbrick** [comment]
Hi! Sorry, I just now noticed your message. That would be great! I assume this logo would appear in the Modules app, yes?

**Comment by Tobaloidee** [comment]
Hi, i think so. what i can provide is the logo in different file formats that you need for that module app

**Comment by josephxbrick** [comment]
That's great. Thank you! The modules image is expected to be square, but looking at various projects' thumbnails the size is all over the place.

**Comment by Tobaloidee** [comment]
okay, ill start designing and post it here wheb done..thanks a lot for the feedback!

**Comment by Tobaloidee** [comment]
Hi @josephxbrick  sorry for the delay.. Here's what i came up with..Favicon and Logotype options to choose from..Still open for your suggestions.

![tabbar-01](https://user-images.githubusercontent.com/36028424/43702872-b259c86a-998d-11e8-8e92-b44df158349b.png)
